DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username   VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `task`;
CREATE TABLE `task` (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id     INT UNSIGNED NOT NULL,
  name        VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  date_time   DATETIME     NOT NULL,
  completed   TINYINT(1)   NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id)
  REFERENCES user (id)
  ON UPDATE CASCADE
  ON DELETE CASCADE,
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE INDEX ON task (user_id);